#!/usr/bin/env bash
#a Bash script that displays to infinity and beyond indefini#tely
# and 'I am invincible!!!' when receiving a SIGTERM signal

for (( f=1; f>0; f++ )) do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
